Disable false positives from clippy
The function parameters are defined by the proc_macro_attribute and
we cannot change them.

Full lint error:
"
error: this argument is passed by value, but not consumed in the function body
  --> intercom-attributes/src/lib.rs:55:11
   |
55 |     attr: TokenStream,
   |           ^^^^^^^^^^^ help: consider taking a reference instead: `&TokenStream`
   |
   = note: `-D needless-pass-by-value` implied by `-D warnings`
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.198/index.html#needless_pass_by_value
"